// Generated by CoffeeScript 1.3.3
(function() {
  var abie;

  abie = require('../lib/abie');

  exports.test = function(test) {
    test.equal(abie.number, 1);
    return test.done();
  };

}).call(this);
