// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    populations: {},
    test: function(name, testCases, options) {
      var counter, defaultCase, probability, random, testCase, _i, _len;
      this.incrementPopulation(name);
      options = options || {};
      defaultCase = testCases[0];
      if ((this.isInactive(options)) || (this.populationReached(name, options))) {
        return defaultCase.name;
      }
      counter = testCases.length;
      for (_i = 0, _len = testCases.length; _i < _len; _i++) {
        testCase = testCases[_i];
        probability = 1 / counter--;
        random = Math.random();
        if (random < probability) {
          return testCase.name;
        }
      }
    },
    incrementPopulation: function(name) {
      if (!this.populations[name]) {
        this.populations[name] = 0;
      }
      return this.populations[name]++;
    },
    populationReached: function(name, options) {
      return options.population && this.populations[name] >= options.population;
    },
    isInactive: function(options) {
      return options.startDate > new Date() || options.endDate < new Date();
    }
  };

}).call(this);
